---
name: 'Install OpenCV'
description: |
  Install OpenCV for Linux CI builds.
  Attempts to install from system packages first, falls back to building from source.

inputs:
  build-from-source:
    description: 'Whether to force building from source'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Update package lists
        sudo apt-get update -y

        # Install build essentials and dependencies
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          cmake \
          build-essential \
          git \
          pkg-config \
          wget \
          unzip \
          yasm \
          checkinstall \
          python3 \
          python3-pip \
          python3-dev \
          python3-numpy \
          libtbb-dev \
          libtbb12 \
          libgtk-3-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          libv4l-dev \
          libxvidcore-dev \
          libx264-dev \
          libatlas-base-dev \
          gfortran \
          libhdf5-dev \
          libhdf5-serial-dev \
          libopenexr-dev \
          libgstreamer1.0-0 \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libxine2-dev \
          libtesseract-dev \
          liblapack-dev \
          libeigen3-dev \
          libgflags-dev \
          libgoogle-glog-dev \
          libprotobuf-dev \
          protobuf-compiler \
          libleveldb-dev \
          liblmdb-dev \
          libsnappy-dev \
          libboost-all-dev \
          libopencv-dev \
          libopenblas-dev \
          gcc-11 g++-11

    - name: Install OpenCV
      shell: bash
      run: |
        # Function to build OpenCV from source
        build_opencv() {
          echo "Building OpenCV from source..."

          # Create build directory
          mkdir -p ~/opencv_build
          cd ~/opencv_build

          # Clone OpenCV and opencv_contrib
          git clone --depth 1 --branch 4.8.0 https://github.com/opencv/opencv.git
          git clone --depth 1 --branch 4.8.0 https://github.com/opencv/opencv_contrib.git

          # Create build directory
          mkdir -p build && cd build

          # Configure with CMake
          cmake \
            -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=/usr/local \
            -D OPENCV_GENERATE_PKGCONFIG=ON \
            -D OPENCV_ENABLE_NONFREE=ON \
            -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
            -D BUILD_EXAMPLES=OFF \
            -D INSTALL_PYTHON_EXAMPLES=OFF \
            -D INSTALL_C_EXAMPLES=OFF \
            -D WITH_TBB=ON \
            -D WITH_V4L=ON \
            -D WITH_QT=OFF \
            -D WITH_OPENGL=ON \
            -D WITH_GSTREAMER=ON \
            -D OPENCV_GENERATE_PKGCONFIG=ON \
            -D CMAKE_C_COMPILER=gcc-11 \
            -D CMAKE_CXX_COMPILER=g++-11 \
            -D BUILD_TESTS=OFF \
            -D BUILD_PERF_TESTS=OFF \
            -D BUILD_opencv_java=OFF \
            -D BUILD_opencv_python2=OFF \
            -D BUILD_opencv_python3=ON \
            -D PYTHON3_EXECUTABLE=$(which python3) \
            -D PYTHON3_INCLUDE_DIR=$(python3 -c \
              "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
            -D PYTHON3_PACKAGES_PATH=$(python3 -c \
              "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \
            -D PYTHON3_LIBRARY=$(python3 -c \
              "from distutils.sysconfig import get_config_var;"\
              "from os.path import dirname,join;"\
              "print(join(dirname(get_config_var('LIBPC')),"\
              "get_config_var('LDLIBRARY')))") \
            ../opencv

          # Build and install
          make -j$(nproc)
          sudo make install
          sudo ldconfig

          # Clean up
          cd ~
          rm -rf ~/opencv_build

          # Set OpenCV_DIR
          echo "OpenCV_DIR=/usr/local/lib/cmake/opencv4" >> $GITHUB_ENV
        }

        # Try to install OpenCV from system packages first
        echo "Attempting to install OpenCV from system packages..."
        if sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            libopencv-dev \
            libopencv-core-dev \
            libopencv-highgui-dev \
            libopencv-imgproc-dev \
            libopencv-imgcodecs-dev \
            libopencv-videoio-dev; then

          echo "OpenCV installed from system packages"

          # Set OpenCV_DIR if found in standard locations
          if [ -d "/usr/lib/x86_64-linux-gnu/cmake/opencv4" ]; then
            echo "OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4" >> $GITHUB_ENV
          elif [ -d "/usr/local/lib/cmake/opencv4" ]; then
            echo "OpenCV_DIR=/usr/local/lib/cmake/opencv4" >> $GITHUB_ENV
          fi
        else
          echo "Failed to install OpenCV from system packages, building from source..."
          build_opencv
        fi

        # Verify OpenCV installation
        echo "Verifying OpenCV installation..."
        if [ -z "$OpenCV_DIR" ]; then
          if [ -d "/usr/lib/x86_64-linux-gnu/cmake/opencv4" ]; then
            export OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4
          elif [ -d "/usr/local/lib/cmake/opencv4" ]; then
            export OpenCV_DIR=/usr/local/lib/cmake/opencv4
          fi
        fi

        if [ -n "$OpenCV_DIR" ]; then
          echo "OpenCV found at: $OpenCV_DIR"
          echo "OpenCV_DIR=$OpenCV_DIR" >> $GITHUB_ENV
        else
          echo "WARNING: OpenCV not found after installation attempts"
          find /usr /opt -name "OpenCVConfig.cmake" -o -name "opencv4.pc" 2>/dev/null || true
        fi
