---
name: 'Install CUDA'
description: 'Install CUDA compiler and libraries for Ubuntu'
runs:
  using: 'composite'
  steps:
    - name: Install CUDA
      shell: bash
      run: |
        export PATH=/usr/bin:/bin:$PATH
        URL="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb"
        /usr/bin/curl -s -o /tmp/cuda-keyring.deb "$URL"
        /usr/bin/sudo /usr/bin/apt install -y /tmp/cuda-keyring.deb
        echo "deb http://archive.ubuntu.com/ubuntu jammy main" | \
          /usr/bin/sudo /usr/bin/tee /etc/apt/sources.list.d/jammy.list
        /usr/bin/sudo /usr/bin/apt-get update
        /usr/bin/sudo /usr/bin/apt-get install -y --no-install-recommends \
          cuda-compiler-12-6 cuda-libraries-12-6 || echo "CUDA installation skipped"
        echo "CUDACXX=nvcc" >> $GITHUB_ENV
        echo "CMAKE_CUDA_ARCHITECTURES=75;80;86" >> $GITHUB_ENV
    - name: Verify CUDA installation
      shell: bash
      run: |
        export PATH=/usr/bin:/bin:$PATH
        /usr/bin/which nvcc
        /usr/bin/nvcc --version
