---
name: 'Install CUDA'
description: 'Install CUDA compiler and libraries for Ubuntu'
runs:
  using: 'composite'
  steps:
    - name: Install CUDA
      shell: bash
      run: bash scripts/install_cuda.sh
