#!/usr/bin/env python3
"""
Enhance the CHANGELOG.md generated by semantic-release.
This script can add additional formatting, links, or custom enhancements.
"""

import os


def enhance_changelog():
    changelog_path = "CHANGELOG.md"
    if not os.path.exists(changelog_path):
        print("CHANGELOG.md not found, skipping enhancement.")
        return

    with open(changelog_path, "r") as f:
        content = f.read()

    # Example enhancement: Add a header if not present
    if not content.startswith("# Changelog"):
        enhanced_content = "# Changelog\n\n" + content
    else:
        enhanced_content = content

    # You can add more enhancements here, like adding links to issues/PRs, etc.

    with open(changelog_path, "w") as f:
        f.write(enhanced_content)

    print("Changelog enhanced successfully.")


if __name__ == "__main__":
    enhance_changelog()
