#!/usr/bin/env python3
"""
Enhance the CHANGELOG.md generated by semantic-release.

Purpose:
- Adds a standard "# Changelog" header if missing.
- Placeholder for future enhancements like adding links to issues/PRs or formatting improvements.

Input:
- CHANGELOG.md file generated by semantic-release.

Output:
- Modified CHANGELOG.md with enhancements.

Dependencies:
- None (uses standard library).

Security Notes:
- Reads and writes only to CHANGELOG.md in the current directory.
- No external network calls or sensitive operations.
"""

import os


def enhance_changelog():
    """
    Enhances the CHANGELOG.md file.

    Checks for the file's existence, adds a header if needed, and applies any additional enhancements.
    """
    changelog_path = "CHANGELOG.md"
    if not os.path.exists(changelog_path):
        print("CHANGELOG.md not found, skipping enhancement.")
        return

    try:
        with open(changelog_path, "r", encoding="utf-8") as f:
            content = f.read()
    except IOError as e:
        print(f"Error reading CHANGELOG.md: {e}")
        return

    # Enhancement 1: Add a header if not present
    if not content.startswith("# Changelog"):
        enhanced_content = "# Changelog\n\n" + content
    else:
        enhanced_content = content

    # Future enhancements can be added here, e.g.:
    # - Add links to GitHub issues/PRs
    # - Format dates or sections

    try:
        with open(changelog_path, "w", encoding="utf-8") as f:
            f.write(enhanced_content)
    except IOError as e:
        print(f"Error writing to CHANGELOG.md: {e}")
        return

    print("Changelog enhanced successfully.")


if __name__ == "__main__":
    enhance_changelog()
