---
name: 'Setup vcpkg'
description: |
  Install vcpkg and dependencies for Windows CI builds.
  Clones vcpkg, checks out the specified baseline, bootstraps, integrates with CMake,
  and installs specified packages.

inputs:
  baseline:
    description: 'vcpkg baseline commit ID'
    required: false
    default: 'latest'
  packages:
    description: 'Space-separated list of packages to install'
    required: true
    default: 'opencv'

runs:
  using: 'composite'
  steps:
    - name: Setup vcpkg
      shell: pwsh
      run: |
        # Clone vcpkg without depth limit to avoid checkout issues
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg

        # Checkout baseline if specified, otherwise use latest
        if ("${{ inputs.baseline }}" -ne "latest") {
          if (git checkout ${{ inputs.baseline }} 2>$null) {
            Write-Host "Checked out baseline: ${{ inputs.baseline }}"
          } else {
            Write-Host "Baseline checkout failed, using latest commit"
          }
        } else {
          Write-Host "Using latest vcpkg commit"
        }

        # Bootstrap vcpkg
        Write-Host "Bootstrapping vcpkg..."
        .\bootstrap-vcpkg.bat
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg bootstrap failed"
          exit 1
        }

        # Verify vcpkg is working
        Write-Host "Verifying vcpkg installation..."
        if (Test-Path ".\vcpkg.exe") {
          Write-Host "vcpkg.exe found successfully"
          Write-Host "Testing vcpkg version command..."
          .\vcpkg.exe version
          Write-Host "Testing vcpkg help command..."
          .\vcpkg.exe help
        } else {
          Write-Error "vcpkg.exe not found after bootstrap"
          exit 1
        }

        # Integrate with CMake
        Write-Host "Integrating vcpkg with CMake..."
        .\vcpkg.exe integrate install
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg integration failed"
          exit 1
        }

        # Install packages - Version 2024-11-02
        $packages = "${{ inputs.packages }}"
        Write-Host "Installing packages: $packages"
        Write-Host "Action version: 2024-11-02-v3"

        # Determine the default triplet for Windows
        $triplet = "x64-windows"
        Write-Host "Using triplet: $triplet"

        # Test basic vcpkg functionality first
        Write-Host "Testing basic vcpkg commands..."
        Write-Host "=== vcpkg list ==="
        .\vcpkg.exe list
        Write-Host "=== vcpkg search opencv ==="
        .\vcpkg.exe search opencv

        # Check if we're in the right directory and vcpkg is properly set up
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "vcpkg.exe exists: $(Test-Path '.\vcpkg.exe')"

        # Try a simple install without any flags first
        Write-Host "=== Attempting simple install ==="
        $packageName = "opencv"
        Write-Host "Installing: $packageName"

        # Use cmd to run vcpkg to avoid PowerShell interpretation issues
        Write-Host "Using cmd to run vcpkg..."
        cmd /c "vcpkg.exe install opencv"

        if ($LASTEXITCODE -ne 0) {
          Write-Host "cmd install failed, trying PowerShell direct..."
          & ".\vcpkg.exe" "install" "opencv"

          if ($LASTEXITCODE -ne 0) {
            Write-Host "Direct PowerShell failed, trying with triplet..."
            & ".\vcpkg.exe" "install" "opencv:x64-windows"

            if ($LASTEXITCODE -ne 0) {
              Write-Error "All vcpkg installation methods failed"
              Write-Host "Listing vcpkg directory contents:"
              Get-ChildItem -Path . -Name
              exit 1
            }
          }
        }

        Write-Host "Package installation completed successfully"
