---
name: 'Setup vcpkg'
description: |
  Install vcpkg and dependencies for Windows CI builds.
  Clones vcpkg, checks out the specified baseline, bootstraps, integrates with CMake,
  and installs specified packages.

inputs:
  baseline:
    description: 'vcpkg baseline commit ID'
    required: false
    default: 'latest'
  packages:
    description: 'Space-separated list of packages to install'
    required: true
    default: 'opencv'

runs:
  using: 'composite'
  steps:
    - name: Setup vcpkg
      shell: pwsh
      run: |
        # Clone vcpkg without depth limit to avoid checkout issues
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg

        # Checkout baseline if specified, otherwise use latest
        if ("${{ inputs.baseline }}" -ne "latest") {
          if (git checkout ${{ inputs.baseline }} 2>$null) {
            Write-Host "Checked out baseline: ${{ inputs.baseline }}"
          } else {
            Write-Host "Baseline checkout failed, using latest commit"
          }
        } else {
          Write-Host "Using latest vcpkg commit"
        }

        # Bootstrap vcpkg
        Write-Host "Bootstrapping vcpkg..."
        .\bootstrap-vcpkg.bat
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg bootstrap failed"
          exit 1
        }

        # Verify vcpkg is working
        Write-Host "Verifying vcpkg installation..."
        if (Test-Path ".\vcpkg.exe") {
          Write-Host "vcpkg.exe found successfully"
          Write-Host "Testing vcpkg version command..."
          .\vcpkg.exe version
          Write-Host "Testing vcpkg help command..."
          .\vcpkg.exe help
        } else {
          Write-Error "vcpkg.exe not found after bootstrap"
          exit 1
        }

        # Integrate with CMake
        Write-Host "Integrating vcpkg with CMake..."
        .\vcpkg.exe integrate install
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg integration failed"
          exit 1
        }

        # Install packages
        $packages = "${{ inputs.packages }}"
        Write-Host "Installing packages: $packages"

        # Determine the default triplet for Windows
        $triplet = "x64-windows"
        Write-Host "Using triplet: $triplet"

        # Split packages and install each one
        $packageList = $packages -split '\s+'
        foreach ($package in $packageList) {
          if ($package.Trim()) {
            $packageName = $package.Trim()
            Write-Host "Installing package: $packageName"
            Write-Host "Running: .\vcpkg.exe install ${packageName}:${triplet}"

            # Install with explicit triplet
            .\vcpkg.exe install "${packageName}:${triplet}"

            if ($LASTEXITCODE -ne 0) {
              Write-Host "Install failed, trying without triplet..."
              .\vcpkg.exe install $packageName
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to install package: $packageName"
                exit 1
              }
            }

            Write-Host "Successfully installed: $packageName"
          }
        }
