---
name: 'Setup vcpkg'
description: |
  Install vcpkg and dependencies for Windows CI builds.
  Clones vcpkg, checks out the specified baseline, bootstraps, integrates with CMake,
  and installs specified packages.

inputs:
  baseline:
    description: 'vcpkg baseline commit ID'
    required: false
    default: 'latest'
  packages:
    description: 'Space-separated list of packages to install'
    required: true
    default: 'opencv'

runs:
  using: 'composite'
  steps:
    - name: Setup vcpkg
      shell: pwsh
      run: |
        # Clone vcpkg without depth limit to avoid checkout issues
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg

        # Checkout baseline if specified, otherwise use latest
        if ("${{ inputs.baseline }}" -ne "latest") {
          if (git checkout ${{ inputs.baseline }} 2>$null) {
            Write-Host "Checked out baseline: ${{ inputs.baseline }}"
          } else {
            Write-Host "Baseline checkout failed, using latest commit"
          }
        } else {
          Write-Host "Using latest vcpkg commit"
        }

        # Bootstrap vcpkg
        Write-Host "Bootstrapping vcpkg..."
        .\bootstrap-vcpkg.bat
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg bootstrap failed"
          exit 1
        }

        # Verify vcpkg is working
        Write-Host "Verifying vcpkg installation..."
        .\vcpkg version

        # Integrate with CMake
        Write-Host "Integrating vcpkg with CMake..."
        .\vcpkg integrate install
        if ($LASTEXITCODE -ne 0) {
          Write-Error "vcpkg integration failed"
          exit 1
        }

        # Install packages
        $packages = "${{ inputs.packages }}"
        Write-Host "Installing packages: $packages"

        # Split packages and install each one
        $packageList = $packages -split '\s+'
        foreach ($package in $packageList) {
          if ($package.Trim()) {
            Write-Host "Installing package: $package"
            .\vcpkg install $package.Trim()
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to install package: $package"
              exit 1
            }
          }
        }
