---
name: 'Setup vcpkg'
description: |
  Install vcpkg and dependencies for Windows CI builds.
  Clones vcpkg, checks out the specified baseline, bootstraps, integrates with CMake,
  and installs specified packages.

inputs:
  baseline:
    description: 'vcpkg baseline commit ID'
    required: false
    default: 'latest'
  packages:
    description: 'Space-separated list of packages to install'
    required: true
    default: 'opencv'

runs:
  using: 'composite'
  steps:
    - name: Setup vcpkg
      shell: pwsh
      run: |
        # Clone vcpkg without depth limit to avoid checkout issues
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg

        # Checkout baseline if specified, otherwise use latest
        if ("${{ inputs.baseline }}" -ne "latest") {
          if (git checkout ${{ inputs.baseline }} 2>$null) {
            Write-Host "Checked out baseline: ${{ inputs.baseline }}"
          } else {
            Write-Host "Baseline checkout failed, using latest commit"
          }
        } else {
          Write-Host "Using latest vcpkg commit"
        }

        # Bootstrap vcpkg
        .\bootstrap-vcpkg.bat

        # Integrate with CMake
        .\vcpkg integrate install

        # Install packages
        .\vcpkg install ${{ inputs.packages }}
