---
name: CI CUDA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cuda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        ./scripts/setup-ci.sh linux cuda

    - name: Build CUDA upscale
      run: |
        if command -v nvcc >/dev/null 2>&1; then
          cd cloud_gpu
          nvcc upscale.cu -o upscale \
            -I/usr/include/opencv4 \
            -lopencv_core -lopencv_imgcodecs
          echo "CUDA upscale built successfully"
          # Test basic execution (no GPU needed for syntax check)
          ./upscale 2>/dev/null || echo "Execution test skipped (no GPU)"
        else
          echo "CUDA not available"
          exit 1
        fi
