---
name: CI CUDA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cuda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libopencv-dev build-essential
        # Install CUDA toolkit
        if wget -q \
          https://developer.download.nvidia.com/compute/cuda/repos/ \
          ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb \
          -O /tmp/cuda-keyring.deb; then
            sudo dpkg -i /tmp/cuda-keyring.deb
            sudo apt-get update
            sudo apt-get install -y cuda-toolkit-12-6 || \
              echo "CUDA installation skipped"
        else
            echo "CUDA keyring download failed, skipping CUDA build"
        fi

    - name: Build CUDA upscale
      run: |
        if command -v nvcc >/dev/null 2>&1; then
          cd cloud_gpu
          nvcc upscale.cu -o upscale \
            -I/usr/include/opencv4 \
            -lopencv_core -lopencv_imgcodecs
          echo "CUDA upscale built successfully"
          # Test basic execution (no GPU needed for syntax check)
          ./upscale 2>/dev/null || echo "Execution test skipped (no GPU)"
        else
          echo "CUDA not available, skipping build"
        fi
