---
name: CI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      timeout-minutes: 5

    - name: Build local Docker image
      timeout-minutes: 20
      run: |
        set -e
        echo "Building local Docker image..."
        docker build -t hybrid-compute . --progress=plain

    - name: Test local Docker image
      timeout-minutes: 10
      run: |
        set -e
        echo "Testing local Docker image..."
        timeout 300 docker run --rm \
          -e DEBIAN_FRONTEND=noninteractive \
          hybrid-compute

    - name: Build CUDA Docker image
      timeout-minutes: 20
      run: |
        set -e
        echo "Building CUDA Docker image..."
        docker build -f Dockerfile.cuda -t hybrid-compute-cuda \
          . --progress=plain

      # Note: CUDA testing requires GPU runners, so only build is tested here
