---
name: CI Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort ruff yamllint

    - name: Run black
      run: black --check --line-length=127 .

    - name: Run isort
      run: isort --check-only --profile black --line-length=127 .

    - name: Run ruff
      run: ruff check .

    - name: Run yamllint
      run: yamllint --strict .
