---
name: CI macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ────────────────────────────── Build & Test macOS ──────────────────────────────
  test-and-build-macos:
    runs-on: macos-latest
    timeout-minutes: 90
    strategy:
      matrix:
        include:
          - config: "metal"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake opencv python3

      - name: Build & Test
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=OFF -DWITH_OPENCV=ON
          make -j$(sysctl -n hw.ncpu)
          ctest --output-on-failure --timeout 300 --parallel $(sysctl -n hw.ncpu)
