---
name: CI Polish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  polish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort ruff yamllint pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files

    - name: Build and test
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libopencv-dev build-essential
        mkdir build
        cd build
        cmake ..
        make
        ctest

    - name: Run Python tests
      run: |
        pip install -r requirements.txt
        python -m pytest tests/ -v
